merge(Fix/doc): reformatage des commentaire
tower-defense-L2/projet-L2 pull request #29
Opened 2023-03-22 10:36 UTC by meo-pill

2023-03-22 10:56 UTC, enimaloc requested changes

2023-03-22 10:56 UTC, enimaloc commented on include/init_supr_sdl.h
> + * \return int // 0 si tout c'est bien passé 1 sinon
Il n’est pas nécessaire de mettre `//` tu te situe déjà dans un commentaire.

2023-03-22 12:25 UTC, enimaloc requested changes
Enlever tout les `\brief` dans le commentaire qui sont contenu dans les blocs de fonction, il ne doivent pas être pris en compte par Doxygen, par conséquent pas besoin de les formater comme tel

2023-03-22 12:25 UTC, enimaloc commented on src/sdl/init_supr_sdl.c
> +     * \brief Supression de la liste de texture en récursivité
La même chose que sur `src/jeux.c`

2023-03-22 12:25 UTC, enimaloc commented on src/sdl/init_supr_sdl.c
> +     * \brief destruction du bouton et libération de la mémoire
La même chose que sur `src/jeux.c`

2023-03-22 12:25 UTC, enimaloc commented on src/sdl/init_supr_sdl.c
> +     * \brief attribution des coordonnées au bouton
La même chose que sur `src/jeux.c`

2023-03-22 12:25 UTC, enimaloc commented on src/sdl/interaction_souris.c
> +     * \brief comparaison de la coordonnée de la souris avec les coordonnées du rectangle
La même chose que sur `src/jeux.c`

2023-03-22 12:25 UTC, enimaloc commented on src/sdl/interaction_souris.c
> +     * \brief si la souris est sur le bouton, on affiche le bouton survol
La même chose que sur `src/jeux.c`

2023-03-24 11:22 UTC, meo-pill commented
À voir si les la doc doit être régénéré avant un push dans le master

2023-03-24 12:18 UTC, enimaloc approved these changes

2023-03-24 12:19 UTC, merged