merge(feat/affichage) : ajout interface et gestion erreur
tower-defense-L2/projet-L2 pull request #55
Opened 2023-04-03 14:47 UTC by meo-pill

2023-04-04 13:26 UTC, enimaloc requested changes

2023-04-04 13:26 UTC, enimaloc commented on include/jeux.h
> + * \return int 0 si tout c'est bien passé 1 sinon
Cela devrait être l'inverse, pour représenté un `boolean`

2023-04-04 13:28 UTC, meo-pill commented on include/jeux.h
> + * \return int 0 si tout c'est bien passé 1 sinon
Non dans ton main tu, mais bien des retrun 0

2023-04-04 13:30 UTC, meo-pill commented on include/jeux.h
> + * \return int 0 si tout c'est bien passé 1 sinon
Et ca permet de faire du debug en message d'erreur

2023-04-04 13:48 UTC, enimaloc commented on include/jeux.h
> + * \return int 0 si tout c'est bien passé 1 sinon
Car c'est la fonction main, le return 0 c'est l'exit code  
  
Par convention dans les exit code, Sortie != 0 -> Erreur

2023-04-04 14:46 UTC, meo-pill commented on include/jeux.h
> + * \return int 0 si tout c'est bien passé 1 sinon
oui mais plus simple en merge

2023-04-05 06:25 UTC, meo-pill commented on include/jeux.h
> + * \return int 0 si tout c'est bien passé 1 sinon
je te fait ca

2023-04-06 21:32 UTC, merged